//! Goal — durable GoalSpec, success criteria, constraints, budget, and approval policy.
//!
//! I7.1: The Goal is the outer loop's immutable contract. GoalSpec fields are
//! set at creation; only the user may modify them (via GoalRevision).
//!
//! All types are pure data. No I/O, no Agent dependencies.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

// ── Typed IDs ──────────────────────────────────────────────────────────

pub type GoalId = String;
pub type CriterionId = String;
pub type ConstraintId = String;

// ── Goal State ─────────────────────────────────────────────────────────

/// Goal lifecycle states.
///
/// Terminal: Succeeded, Failed, Cancelled.
/// Active states can re-enter Planning (creates new PlanRevision, NEVER
/// overwrites old one).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GoalState {
    /// Initial state — GoalSpec written but not yet validated.
    Draft,
    /// Schema + constraint validation passed.
    Validated,
    /// Planner is producing an initial PlanProposal.
    Planning,
    /// At least one PlanRevision is Active; tasks may be dispatched.
    Active,
    /// Waiting for user input (approval, information, decision).
    WaitingForApproval,
    /// Explicitly paused by user.
    Paused,
    /// Blocked by infrastructure or external dependency.
    Blocked,
    // ── Terminal ──
    /// All required success criteria satisfied, verified, and approved.
    Succeeded,
    /// Goal cannot be completed (budget exhausted, unrecoverable failure).
    Failed,
    /// Explicitly cancelled by user.
    Cancelled,
}

impl GoalState {
    pub fn is_terminal(&self) -> bool {
        matches!(self, Self::Succeeded | Self::Failed | Self::Cancelled)
    }

    pub fn is_active(&self) -> bool {
        matches!(
            self,
            Self::Planning | Self::Active | Self::WaitingForApproval | Self::Paused
        )
    }

    pub fn can_dispatch_tasks(&self) -> bool {
        matches!(self, Self::Active)
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Draft => "draft",
            Self::Validated => "validated",
            Self::Planning => "planning",
            Self::Active => "active",
            Self::WaitingForApproval => "waiting_for_approval",
            Self::Paused => "paused",
            Self::Blocked => "blocked",
            Self::Succeeded => "succeeded",
            Self::Failed => "failed",
            Self::Cancelled => "cancelled",
        }
    }
}

// ── GoalSpec ───────────────────────────────────────────────────────────

/// The immutable contract for a Goal. System fields (goal_id, revision,
/// created_at) are generated by the Harness — the Planner may NOT specify them.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalSpec {
    /// System-generated unique identifier.
    pub goal_id: GoalId,
    /// Monotonic revision number (1-based).
    pub revision: i64,

    /// Human-readable title.
    pub title: String,
    /// Detailed objective description.
    pub objective: String,

    /// Target repository identifier.
    pub repository_id: String,
    /// Target Git ref for integration.
    pub target_ref: String,
    /// HEAD commit at Goal creation.
    pub initial_base_head: String,

    /// Required success criteria.
    pub success_criteria: Vec<SuccessCriterion>,
    /// Hard constraints on execution.
    pub constraints: Vec<GoalConstraint>,
    /// Explicit non-goals (scope boundary).
    pub non_goals: Vec<String>,

    /// Resource budget.
    pub budget: GoalBudget,
    /// Approval and human-in-the-loop policy.
    pub approval_policy: ApprovalPolicy,

    /// Who created this goal.
    pub created_by: GoalCreator,
    /// When this goal was created.
    pub created_at: DateTime<Utc>,
}

// ── SuccessCriterion ───────────────────────────────────────────────────

/// A single measurable success criterion for a Goal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SuccessCriterion {
    /// Unique identifier within this Goal (system-generated).
    pub criterion_id: CriterionId,
    /// Human-readable description of what must be achieved.
    pub description: String,
    /// What kind of evidence satisfies this criterion.
    pub evidence_policy: EvidencePolicy,
    /// How the evidence is verified.
    pub verification_policy: VerificationPolicy,
    /// Whether this criterion requires subjective (human) judgment.
    pub subjectivity: CriterionSubjectivity,
    /// If true, this criterion MUST be satisfied for Goal success.
    pub required: bool,
}

/// What kind of evidence satisfies a criterion.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EvidencePolicy {
    /// Task reached terminal state (Done, Verified).
    TaskTerminalResult,
    /// A specific verification command must pass.
    VerificationCommand { command: String },
    /// A review decision of Approved.
    ReviewDecision,
    /// A commit OID must exist in the target repository.
    CommitOid,
    /// IntegrationResult must be Integrated.
    IntegratedTargetHead,
    /// A file or artifact must have a specific digest.
    FileDigest { path: String, algorithm: String },
    /// Structured user approval is required (always subjective).
    StructuredUserApproval,
    /// External evidence that requires user input to provide.
    ExternalEvidence { description: String },
}

/// How evidence should be verified.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationPolicy {
    /// Evidence existence + schema validation only.
    ExistenceOnly,
    /// Content must match expected digest.
    DigestMatch,
    /// A deterministic script is run.
    DeterministicScript { script: String },
    /// Requires human judgment (always with subjectivity).
    HumanReview,
}

/// Whether a criterion requires subjective human judgment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CriterionSubjectivity {
    /// Objective — can be verified automatically.
    Objective,
    /// Subjective — requires human approval.
    Subjective,
}

impl CriterionSubjectivity {
    pub fn requires_human_approval(&self) -> bool {
        matches!(self, Self::Subjective)
    }
}

// ── GoalConstraint ─────────────────────────────────────────────────────

/// A hard constraint on Goal execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalConstraint {
    pub constraint_id: ConstraintId,
    pub description: String,
    pub constraint_type: ConstraintType,
    /// If true, violation immediately blocks the Goal.
    pub blocking: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ConstraintType {
    /// Must not modify specific files.
    FileExclusion { paths: Vec<String> },
    /// Must not exceed resource limits.
    ResourceLimit { resource: String, max_value: String },
    /// Must not use specific tools or commands.
    ToolExclusion { tools: Vec<String> },
    /// Must not change specific behaviors.
    BehaviorConstraint { description: String },
    /// Custom constraint with name.
    Custom { name: String, spec: String },
}

// ── GoalBudget ─────────────────────────────────────────────────────────

/// Resource budget for a Goal. Only the user may increase these values.
/// The Planner and Replanner MUST NOT raise the budget.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalBudget {
    /// Maximum number of PlanRevisions (including the initial plan).
    pub max_plan_revisions: u32,
    /// Maximum total tasks across all revisions.
    pub max_total_tasks: u32,
    /// Maximum concurrently active tasks.
    pub max_active_tasks: u32,
    /// Maximum consecutive task failures before blocking.
    pub max_consecutive_failures: u32,
    /// Maximum loop iterations with no progress before pausing.
    pub max_no_progress_iterations: u32,
    /// Maximum total agent invocations across all tasks.
    pub max_total_agent_invocations: u32,
    /// Maximum Planner invocations (including initial plan).
    pub max_planner_invocations: u32,
    /// Maximum GoalEvaluator invocations.
    pub max_evaluator_invocations: u32,
    /// Maximum wall-clock duration in seconds.
    pub max_elapsed_seconds: u64,
}

impl Default for GoalBudget {
    fn default() -> Self {
        Self {
            max_plan_revisions: 5,
            max_total_tasks: 20,
            max_active_tasks: 4,
            max_consecutive_failures: 3,
            max_no_progress_iterations: 5,
            max_total_agent_invocations: 50,
            max_planner_invocations: 5,
            max_evaluator_invocations: 10,
            max_elapsed_seconds: 3600, // 1 hour
        }
    }
}

impl GoalBudget {
    /// Returns true if any budget has been exhausted.
    pub fn is_exhausted(
        &self,
        plan_revisions_used: u32,
        total_tasks_used: u32,
        planner_invocations_used: u32,
        evaluator_invocations_used: u32,
        agent_invocations_used: u32,
    ) -> bool {
        plan_revisions_used >= self.max_plan_revisions
            || total_tasks_used >= self.max_total_tasks
            || planner_invocations_used >= self.max_planner_invocations
            || evaluator_invocations_used >= self.max_evaluator_invocations
            || agent_invocations_used >= self.max_total_agent_invocations
    }
}

// ── ApprovalPolicy ─────────────────────────────────────────────────────

/// Policy controlling when human approval is required.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApprovalPolicy {
    /// Require approval for the initial plan before activation.
    pub require_initial_plan_approval: bool,
    /// Require approval for high-risk tasks before dispatch.
    pub require_high_risk_task_approval: bool,
    /// Require approval for any scope change.
    pub require_scope_change_approval: bool,
    /// Require approval for any budget increase.
    pub require_budget_increase_approval: bool,
    /// Require approval for Goal completion.
    pub require_completion_approval: bool,
    /// Require approval after no-progress pause.
    pub require_resume_after_no_progress_approval: bool,
    /// Maximum time an approval request can remain pending (seconds).
    pub approval_timeout_secs: u64,
}

impl Default for ApprovalPolicy {
    fn default() -> Self {
        Self {
            require_initial_plan_approval: false,
            require_high_risk_task_approval: true,
            require_scope_change_approval: true,
            require_budget_increase_approval: true,
            require_completion_approval: false,
            require_resume_after_no_progress_approval: true,
            approval_timeout_secs: 86400, // 24 hours
        }
    }
}

// ── GoalCreator ────────────────────────────────────────────────────────

/// Who or what created this Goal.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum GoalCreator {
    /// Created by a human user.
    User {
        user_id: String,
        user_name: Option<String>,
    },
    /// Created programmatically (e.g., by another system).
    System {
        component: String,
        reason: String,
    },
}

// ── GoalRevision ───────────────────────────────────────────────────────

/// An immutable revision of a GoalSpec. Created when the user modifies the
/// Goal. Old revisions are never overwritten.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GoalRevision {
    /// System-generated unique identifier.
    pub goal_revision_id: String,
    pub goal_id: GoalId,
    pub revision_number: i64,

    /// The complete snapshot of the GoalSpec at this revision.
    pub spec_snapshot: serde_json::Value,
    /// Digest of the spec for integrity.
    pub spec_digest: String,

    /// Who or what created this revision.
    pub created_by: String,
    /// Reason for the revision.
    pub reason: String,

    pub created_at: DateTime<Utc>,
}

// ── Tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_goal_state_terminal() {
        assert!(GoalState::Succeeded.is_terminal());
        assert!(GoalState::Failed.is_terminal());
        assert!(GoalState::Cancelled.is_terminal());
        assert!(!GoalState::Draft.is_terminal());
        assert!(!GoalState::Active.is_terminal());
        assert!(!GoalState::Planning.is_terminal());
    }

    #[test]
    fn test_goal_state_can_dispatch() {
        assert!(GoalState::Active.can_dispatch_tasks());
        assert!(!GoalState::Draft.can_dispatch_tasks());
        assert!(!GoalState::Planning.can_dispatch_tasks());
        assert!(!GoalState::Succeeded.can_dispatch_tasks());
    }

    #[test]
    fn test_subjectivity_requires_human() {
        assert!(CriterionSubjectivity::Subjective.requires_human_approval());
        assert!(!CriterionSubjectivity::Objective.requires_human_approval());
    }

    #[test]
    fn test_budget_default_not_exhausted() {
        let budget = GoalBudget::default();
        assert!(!budget.is_exhausted(0, 0, 0, 0, 0));
    }

    #[test]
    fn test_budget_exhausted_plan_revisions() {
        let budget = GoalBudget::default();
        assert!(budget.is_exhausted(5, 0, 0, 0, 0));
    }

    #[test]
    fn test_budget_exhausted_total_tasks() {
        let budget = GoalBudget::default();
        assert!(budget.is_exhausted(0, 20, 0, 0, 0));
    }

    #[test]
    fn test_budget_exhausted_planner() {
        let budget = GoalBudget::default();
        assert!(budget.is_exhausted(0, 0, 5, 0, 0));
    }

    #[test]
    fn test_budget_exhausted_evaluator() {
        let budget = GoalBudget::default();
        assert!(budget.is_exhausted(0, 0, 0, 10, 0));
    }

    #[test]
    fn test_budget_exhausted_agent() {
        let budget = GoalBudget::default();
        assert!(budget.is_exhausted(0, 0, 0, 0, 50));
    }

    #[test]
    fn test_goal_state_as_str() {
        assert_eq!(GoalState::Draft.as_str(), "draft");
        assert_eq!(GoalState::Active.as_str(), "active");
        assert_eq!(GoalState::Succeeded.as_str(), "succeeded");
    }
}
