//! Verification contracts — deterministic post-execution quality checks.
//!
//! A VerificationPlan is an explicit, deterministic list of checks to run
//! against a completed Agent execution. Plans are never generated by LLMs
//! or Agent output — they are templates derived from task configuration.
//!
//! All types are pure data. No I/O, no external process dependencies.

use serde::{Deserialize, Serialize};

// ── VerificationPlan ──────────────────────────────────────────────────

/// A deterministic, explicitly-configured list of verification steps.
/// Never generated by LLM or Agent output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationPlan {
    pub plan_id: String,
    pub task_id: String,
    pub execution_id: String,
    pub project_id: String,
    /// Ordered list of verification steps.
    pub steps: Vec<VerificationStep>,
    /// Cryptographic fingerprint of the plan content (for idempotency).
    pub fingerprint: VerificationPlanFingerprint,
    /// Schema version for forward compatibility.
    pub plan_version: u32,
    pub created_at: String,
}

/// Stable fingerprint of a VerificationPlan. Used for idempotency:
/// same plan + same execution → same VerificationRun.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct VerificationPlanFingerprint {
    /// Hash of the serialized plan (steps + config, excluding timestamps).
    pub plan_hash: String,
    /// The execution this plan was generated for.
    pub execution_id: String,
    /// Schema version at generation time.
    pub plan_version: u32,
}

impl VerificationPlanFingerprint {
    /// Compute an idempotency key from the fingerprint and execution.
    pub fn idempotency_key(&self) -> String {
        format!("verify-{}-{}", self.execution_id, self.plan_hash)
    }
}

// ── VerificationStep ──────────────────────────────────────────────────

/// A single atomic verification check.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationStep {
    pub step_id: String,
    pub plan_id: String,
    /// The kind of check this step performs.
    pub kind: VerificationStepKind,
    /// Human-readable description.
    pub description: String,
    /// Whether this step must pass for overall verification to succeed.
    pub required: bool,
    /// Step ordering within the plan (0-indexed).
    pub sequence_index: u32,
    /// Step-specific configuration (never contains secrets or credentials).
    pub config_json: String,
}

/// Categories of verification steps.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationStepKind {
    /// Verify working tree diff is clean, expected, or within policy.
    GitDiffCheck,
    /// Verify changed files are within the task's FileScope.
    FileScopeCheck,
    /// Scan changed content for secrets, tokens, or sensitive patterns.
    SecretScanCheck,
    /// Verify command policy compliance (allowed commands, no denied patterns).
    PolicyCheck,
    /// Run acceptance checks from the task definition.
    AcceptanceCheck,
    /// Verify artifact integrity and existence.
    ArtifactCheck,
    /// Verify the TaskResult structure is valid.
    TaskResultCheck,
    /// Verify the worktree is in the expected state.
    WorktreeCheck,
    /// Verify lease and claim ownership is valid.
    ResourceOwnershipCheck,
    /// Custom check with an opaque config.
    CustomCheck,
}

// ── VerificationRun ───────────────────────────────────────────────────

/// A single execution of a VerificationPlan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationRun {
    pub run_id: String,
    pub plan_id: String,
    pub plan_fingerprint: VerificationPlanFingerprint,
    pub execution_id: String,
    pub task_id: String,
    pub project_id: String,
    /// Runtime lifecycle state.
    pub lifecycle: VerificationRunLifecycle,
    /// Idempotency identity.
    pub idempotency_key: String,
    /// Hash of the dispatch request that triggered this run.
    pub request_hash: String,
    /// When the run was created.
    pub created_at: String,
    /// When the run started executing.
    pub started_at: Option<String>,
    /// When the run reached a terminal state.
    pub completed_at: Option<String>,
    /// Terminal outcome (set when lifecycle becomes terminal).
    pub outcome: Option<VerificationOutcome>,
    /// Version for optimistic locking.
    pub version: i64,
}

/// Lifecycle of a VerificationRun.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationRunLifecycle {
    /// Run created but not yet started.
    Created,
    /// Verification steps are actively being executed.
    Running,
    /// All steps completed successfully.
    Completed,
    /// Verification found issues (see outcome for classification).
    Failed,
    /// Verification was cancelled externally.
    Cancelled,
    /// Verification encountered an infrastructure error.
    Error,
}

impl VerificationRunLifecycle {
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            Self::Completed | Self::Failed | Self::Cancelled | Self::Error
        )
    }

    pub fn is_active(&self) -> bool {
        matches!(self, Self::Created | Self::Running)
    }
}

// ── VerificationStepResult ────────────────────────────────────────────

/// Outcome of a single verification step execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationStepResult {
    pub result_id: String,
    pub run_id: String,
    pub step_id: String,
    pub plan_id: String,
    /// Step execution status.
    pub status: VerificationStepStatus,
    /// Structured detail (never contains raw secrets or credentials).
    pub detail_json: Option<String>,
    /// When the step started.
    pub started_at: Option<String>,
    /// When the step completed.
    pub completed_at: Option<String>,
    /// Duration in milliseconds.
    pub duration_ms: Option<u64>,
    /// Error message if the step failed with an error.
    pub error_message: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationStepStatus {
    /// Step passed successfully.
    Passed,
    /// Step found issues (non-blocking).
    Failed,
    /// Step found issues that block verification.
    Blocked,
    /// Step was skipped (not applicable or optimised out).
    Skipped,
    /// Step encountered an infrastructure error.
    Error,
    /// Process termination could not be confirmed — the OS may still be
    /// running the process tree. Completion MUST be blocked.
    ProcessUnknown,
}

// ── VerificationEvidence ──────────────────────────────────────────────

/// Structured evidence produced during verification.
/// Never contains raw secrets, credentials, or full log dumps.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationEvidence {
    pub evidence_id: String,
    pub run_id: String,
    pub step_id: String,
    /// Evidence category.
    pub evidence_kind: VerificationEvidenceKind,
    /// One-line summary suitable for display.
    pub summary: String,
    /// Structured detail (references to persisted artifacts, never inline secrets).
    pub detail_json: Option<String>,
    /// Reference to an external artifact file (if detail is large).
    pub artifact_ref: Option<String>,
    /// When the evidence was collected.
    pub collected_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationEvidenceKind {
    /// File diff summary (file paths, change counts — never full content).
    FileDiffSummary,
    /// A secret or token was detected (location + pattern type — never the secret itself).
    SecretFinding,
    /// A policy violation was detected.
    PolicyViolation,
    /// Acceptance test output (summary + artifact ref).
    TestOutput,
    /// Reference to a captured artifact.
    ArtifactRef,
    /// Worktree state summary.
    WorktreeState,
    /// Resource ownership evidence.
    ResourceOwnership,
    /// Custom evidence.
    Custom,
}

// ── VerificationOutcome ───────────────────────────────────────────────

/// Terminal outcome of a VerificationRun.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationOutcome {
    /// Overall result.
    pub result: VerificationResult,
    /// Classification if verification failed.
    pub failure_classification: Option<FailureClassification>,
    /// Human-readable summary.
    pub summary: String,
    /// List of blocking issues.
    pub blockers: Vec<String>,
    /// Total number of findings across all steps.
    pub findings_count: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationResult {
    /// All required steps passed.
    Passed,
    /// Some non-required steps failed but verification is acceptable.
    PassedWithWarnings,
    /// One or more required steps failed.
    Failed,
    /// Verification was blocked by an infrastructure or resource issue.
    Blocked,
    /// Verification encountered an unrecoverable error.
    Error,
}

impl VerificationResult {
    pub fn is_success(&self) -> bool {
        matches!(self, Self::Passed | Self::PassedWithWarnings)
    }
}

// ── FailureClassification ─────────────────────────────────────────────

/// Categorised reason for verification failure.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FailureClassification {
    /// A secret, token, or credential was found in the diff.
    SecretExposure { pattern_count: u32 },
    /// A command policy rule was violated.
    PolicyViolation { rule_count: u32 },
    /// Changes are outside the allowed file scope.
    ScopeViolation { out_of_scope_files: Vec<String> },
    /// One or more acceptance checks failed.
    AcceptanceTestFailure { failed_checks: Vec<String> },
    /// An artifact is missing or corrupted.
    ArtifactCorruption { artifact_ids: Vec<String> },
    /// Verification timed out.
    TimeoutExpired { duration_ms: u64 },
    /// An infrastructure error prevented verification.
    InfrastructureError { reason: String },
    /// Resource contention prevented verification.
    ResourceContention { resource: String },
}

impl FailureClassification {
    pub fn category_name(&self) -> &'static str {
        match self {
            Self::SecretExposure { .. } => "secret_exposure",
            Self::PolicyViolation { .. } => "policy_violation",
            Self::ScopeViolation { .. } => "scope_violation",
            Self::AcceptanceTestFailure { .. } => "acceptance_test_failure",
            Self::ArtifactCorruption { .. } => "artifact_corruption",
            Self::TimeoutExpired { .. } => "timeout_expired",
            Self::InfrastructureError { .. } => "infrastructure_error",
            Self::ResourceContention { .. } => "resource_contention",
        }
    }

    /// Whether this classification should block automatic retry.
    pub fn blocks_retry(&self) -> bool {
        matches!(
            self,
            Self::SecretExposure { .. } | Self::ScopeViolation { .. }
        )
    }
}

// ── VerificationDiagnostic ────────────────────────────────────────────

/// Diagnostic information for debugging verification issues.
/// Never contains credentials, tokens, or raw secrets.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationDiagnostic {
    pub diagnostic_id: String,
    pub run_id: String,
    pub level: VerificationDiagnosticLevel,
    pub message: String,
    pub context_json: Option<String>,
    pub created_at: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum VerificationDiagnosticLevel {
    Info,
    Warning,
    Error,
}

// ── VerificationPlanTemplate ──────────────────────────────────────────

/// A template for constructing a VerificationPlan from task configuration.
/// Plans are instantiated deterministically from these templates — never
/// by LLM or Agent output.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationPlanTemplate {
    pub template_id: String,
    /// Human-readable name.
    pub label: String,
    /// The steps this template adds to every plan.
    pub steps: Vec<VerificationStepTemplate>,
    /// Template version.
    pub version: u32,
}

/// A single step in a plan template. The template is resolved into
/// a concrete VerificationStep at plan creation time.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerificationStepTemplate {
    pub kind: VerificationStepKind,
    pub description: String,
    pub required: bool,
    pub sequence_index: u32,
    /// JSON configuration that may reference task/envelope fields via
    /// `{task_id}`, `{execution_id}`, etc. — these are resolved at
    /// plan creation time.
    pub config_template: String,
}
