-- Migration 012: Verification — deterministic post-execution quality checks.
-- Additive only — migrations 001–011 are frozen.
--
-- A VerificationPlan is an explicit, deterministic list of checks. Plans are
-- never generated by LLM or Agent output.
--
-- A VerificationRun is a single execution of a plan. Idempotent: same plan
-- fingerprint + same request hash returns the existing run.
--
-- VerificationEvidence captures structured findings. Never contains:
--   - lease tokens
--   - credentials or API keys
--   - environment variable values
--   - raw secrets
--   - full log dumps or large diffs

-- ── VerificationPlans ──────────────────────────────────────────────

CREATE TABLE verification_plans (
    plan_id TEXT PRIMARY KEY NOT NULL,
    task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    execution_id TEXT NOT NULL REFERENCES execution_attempts(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    plan_hash TEXT NOT NULL,
    plan_version INTEGER NOT NULL DEFAULT 1,
    steps_json TEXT NOT NULL DEFAULT '[]',
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE UNIQUE INDEX idx_verification_plan_execution
    ON verification_plans(execution_id);

CREATE INDEX idx_verification_plan_task
    ON verification_plans(task_id);

-- ── VerificationRuns ───────────────────────────────────────────────

CREATE TABLE verification_runs (
    run_id TEXT PRIMARY KEY NOT NULL,
    plan_id TEXT NOT NULL REFERENCES verification_plans(plan_id) ON DELETE CASCADE,
    plan_hash TEXT NOT NULL,
    plan_version INTEGER NOT NULL DEFAULT 1,
    execution_id TEXT NOT NULL REFERENCES execution_attempts(id) ON DELETE CASCADE,
    task_id TEXT NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    lifecycle TEXT NOT NULL DEFAULT 'created',
    idempotency_key TEXT NOT NULL UNIQUE,
    request_hash TEXT NOT NULL,
    outcome_json TEXT,
    version INTEGER NOT NULL DEFAULT 1,
    created_at TEXT NOT NULL DEFAULT (datetime('now')),
    started_at TEXT,
    completed_at TEXT,
    updated_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_verification_runs_plan ON verification_runs(plan_id);
CREATE INDEX idx_verification_runs_execution ON verification_runs(execution_id);
CREATE INDEX idx_verification_runs_task ON verification_runs(task_id);
CREATE UNIQUE INDEX idx_verification_runs_one_active_per_execution
    ON verification_runs(execution_id)
    WHERE lifecycle IN ('created', 'running');

-- ── VerificationStepResults ────────────────────────────────────────

CREATE TABLE verification_step_results (
    result_id TEXT PRIMARY KEY NOT NULL,
    run_id TEXT NOT NULL REFERENCES verification_runs(run_id) ON DELETE CASCADE,
    step_id TEXT NOT NULL,
    plan_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    detail_json TEXT,
    started_at TEXT,
    completed_at TEXT,
    duration_ms INTEGER,
    error_message TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_step_results_run ON verification_step_results(run_id);
CREATE INDEX idx_step_results_step ON verification_step_results(step_id);

-- ── VerificationEvidence ───────────────────────────────────────────

CREATE TABLE verification_evidence (
    evidence_id TEXT PRIMARY KEY NOT NULL,
    run_id TEXT NOT NULL REFERENCES verification_runs(run_id) ON DELETE CASCADE,
    step_id TEXT NOT NULL,
    evidence_kind TEXT NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    detail_json TEXT,
    artifact_ref TEXT,
    collected_at TEXT NOT NULL DEFAULT (datetime('now')),
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_evidence_run ON verification_evidence(run_id);
CREATE INDEX idx_evidence_step ON verification_evidence(step_id);
CREATE INDEX idx_evidence_kind ON verification_evidence(evidence_kind);

-- ── VerificationDiagnostics ────────────────────────────────────────

CREATE TABLE verification_diagnostics (
    diagnostic_id TEXT PRIMARY KEY NOT NULL,
    run_id TEXT NOT NULL REFERENCES verification_runs(run_id) ON DELETE CASCADE,
    level TEXT NOT NULL DEFAULT 'info',
    message TEXT NOT NULL,
    context_json TEXT,
    created_at TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE INDEX idx_diagnostics_run ON verification_diagnostics(run_id);
